### ISSUE TITLE
Enable access to cached simulation data during test suite execution

### ISSUE THREAD

**Issue by aphearin** [aphearin/halotools#17]
The branch illustrating the minimal example is called cache_testing. There is a single test file located here: 

halotools/sim_manager/tests/test_cached_simulations.py 

The only thing this test function does is try to load the default halo catalog (Rockstar halos in the Bolshoi simulation at redshift 0). My code raises an IOError (defined by me) when executing this function because no halo catalog is found in that location. 

```
E           IOError: No processed halo catalogs found in cache  for simname = bolshoi and halo-finder = rockstar

halotools/sim_manager/read_nbody.py:151: IOError
```

However, when this exact same line of code is executed outside of the py.test context, the code has no problem detecting the presence of the catalog. 

cc @cdeil @eteq

**Comment by aphearin** [comment]
I should add that the purpose is not merely to test that the astropy get_cache_dir function works properly. The purpose is to implement a blackbox test of the end result of the entire process of reading ASCII data, making cuts on columns and rows, creating new convenience columns, creating self-consistent metadata, and storing the result to the correct subdirectory of the cache.

**Comment by cdeil** [comment]
@aphearin – Well, maybe what's different when running the example via `python setup.py test` is that a different temp cache is accessed and that cache is empty?

Does this help? https://github.com/astropy/astropy/issues/3057#issuecomment-60681195

I'm out of time for today, but FYI: it's much easier for someone to help quickly if you:
1. post the full log of the command you executed and the output you got (e.g. tests can be run via `python setup.py test` or `py.test` or `python -c 'import halotools; halotools.test()'` and might behave differently concerning environment setup)) If the output is really long https://gist.github.com/ is a good way to post it and then link to it from the issue.
2. make it easy to look at the relevant code. From your description it sounds like it's this? https://github.com/astropy/halotools/compare/master...aphearin:cache_testing

**Comment by cdeil** [comment]
There's one trick I sometimes use with `py.test` ... add print statements to the test code (e.g. to print the location or even files in your cache) and then put `1/0` or any other statement that raises an error. If an error is raised, py.test will print the `stdout` and `stderr` output to the console, so this is a poor man's debugging system for issues that only show up in the test runner.

**Comment by aphearin** [comment]
Roger that, @cdeil . You might have noticed that astropy/astropy#3057 (comment) was actually raised by me last October. I have been kicking this can down the road since then, but it won't kick no more, and I need to solve it presently. Apparently this class of problem is just pretty specific to the kind of analysis I'm doing. I guess astropy/astropy#3057 should just be closed if this is not a relevant problem outside of my package. I'll figure something else out. Thanks again for giving this a look.

**Comment by embray** [comment]
I think all that's needed here is an easy way to specify, on a per-test, per-module, or even global basis which cache location to use.  By default the test runner just sets `XDG_CACHE_HOME` to be inside the temporary test directory so it doesn't interfere with, for example, the user's actual `~/.astropy/cache`.  But that can easily be modified on an as-needed basis.

**Comment by aphearin** [comment]
@embray - ok, I think I see at least part of what's going on. The line responsible for the alteration of the cache directory from within the testing environment is in astropy/utils/tests/test_data.py:

monkeypatch.delenv(str('XDG_CACHE_HOME'))

So XDG_CACHE_HOME is being set to None, and somehow this triggers a different behavior of get_cache_dir. However, when looking at the code for get_cache_dir, I don't see what changes here. I'm probably misinterpreting, but it looks like if xch is None, then the function should still return the astropy cache directory. What am I missing?

**Comment by aphearin** [comment]
Ok, well without understanding really what is going on with the XDG_CACHE_HOME variable, I seem to have hacked my way to a formulation of the test that does not fail. However, it makes me pretty nervous to manually change what seems like an important environment variable that I have such poor understanding of. If you could just verify that I'm not doing something dangerous here, I would greatly appreciate it. My solution is here:

https://github.com/astropy/halotools/compare/master...aphearin:cache_testing

cc @embray

**Comment by cdeil** [comment]
I don't know, will this work on systems that don't have `XDG_CACHE_HOME` set like Mac or Windows?

**Comment by embray** [comment]
Most systems don't set that environment variable by default (since the standard that defines it provides a sensible default).  Changing (or setting) the `XDG_CACHE_HOME` environment variable, especially in the context of running some tests for a Python package, has little to no danger (it won't affect other software using the same environment variables).

The code that enables use of the file cache (e.g. `download_file`) calls a function of no arguments called `get_cache_dir()` in order to find out where it should go looking for the cache.  If `XDG_CACHE_HOME` is set, and the directory it's set to exists, it will use that directory to store the cache database and cached files.  So for the sake of running tests I would recommend setting that to something reusable.  (If `XDG_CACHE_HOME` is set and the directory it's set to doesn't exist I _think_ it gets created, but I'm not sure, and I don't know if the documentation is any more clear on that (probably not, from what I've gathered :)).

But that's all it comes down to, essentially.  Having a better way to select the cache location on a case-by-case bases would be useful though, I think.

**Comment by aphearin** [comment]
Many thanks, @embray and @cdeil for the close look at the code. I agree with you that it's simpler/more natural to simply unset the environment variable and reset it. I implemented this behavior as a decorator so that I can use this throughout my test suite. This is going to make my life so much easier. 

https://github.com/astropy/halotools/compare/master...aphearin:cache_testing
