### ISSUE TITLE
Potential bug in marked cross-correlation function

### ISSUE THREAD

**Issue by aphearin** [aphearin/halotools#22]
@duncandc - can you have a look at the new test `test_marked_tpcf_cross_consistency` I have written in `mock_observables/test_clustering/test_marked_tpcf.py`? 

The commit is here: https://github.com/aphearin/halotools/commit/48afce4af3214e723f311db41790e3a61f7b70c7

Is the test I have written a wrong-test, or is there an inconsistency between the marked correlation function results obtained with different do_auto, do_cross choices?

**Comment by duncandc** [comment]
@aphearin  Without looking in lots of detail, try the test with normalize_by set to 'number_counts'.  The default is by 'random_marks'.  Normalizing by 'random_marks' will contain some random noise.

**Comment by aphearin** [comment]
Yup, that did the trick. Thanks!

https://github.com/aphearin/halotools/commit/3a492f750f1d5e750e985650701889b5116eeff8
