### ISSUE TITLE
Bug in doctest for cacciato09 module

### ISSUE THREAD

**Issue by aphearin** [aphearin/halotools#32]
@johannesulf - When I execute the doctest written in the following module, the test never terminates:

https://github.com/johannesulf/halotools/blob/cacciato09_dev/halotools/empirical_models/composite_models/hod_models/cacciato09.py

Do you see the same thing?

**Comment by johannesulf** [comment]
Yes, the reason is the wrong threshold. Should be 11, not 10**11. Python just goes into a neverending loop when asked to calculate `10**(10**11)`. If it was 1e11 instead it would have crashed with some reasonable error message.

**Comment by aphearin** [comment]
Roger, I just confirmed. Closing this issue.
